hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8887
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quanlynhanvien
    username: root
    password: 10112002
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
