hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8887
spring:
  app:
    datasource1:
      url: jdbc:mysql://localhost:3306/quanlynhanvien
      username: root
      password: 10112002
      dataSourceClassName: com.mysql.cj.jdbc.Driver

  security:
    datasource2:
      url: jdbc:mysql://localhost:3306/spring_security
      username: root
      password: 10112002
      dataSourceClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



#    tao ra 1 DB chua pass rieng
#    user:
#      name: long
#      password: quanlysinhvien.vn
#      roles: user

